- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - ec2_instance_facts:
        filters:
          "tag:Name": ansible-cluster-deploy-demo

    - name: terminate matching ec2 instances
      ec2:
        state: absent
        instance_ids: "{{ hostvars[host]['ec2_id'] }}"
