# Stop target ec2 instances and mark them for deletion.
# No dependency on ec2.py or ec2.ini

- hosts: localhost 
  name: Gather hosts
  gather_facts: false

  tasks:
  - ec2_instance_facts:
      filters:
        "tag:Name": "{{ tag_name }}"
      region: "{{ region }}"
    register: ec2_facts

  - add_host:
      hostname: "{{ item.instance_id }}"
      region: "{{ region }}"
      group: ec2hosts
    loop: "{{ ec2_facts.instances }}"


- hosts: ec2hosts
  name: Shutdown hosts
  gather_facts: false 

  tasks:
  - name: stopping instances 
    ec2:
      region: "{{ hostvars[inventory_hostname].region }}"
      instance_id: "{{ inventory_hostname  }}"
      state: stopped
      wait: true
    delegate_to: localhost

  - name: marking instances for deletion
    ec2_tag:
      resource: "{{ inventory_hostname }}"
      region: "{{ hostvars[inventory_hostname].region }}"
      state: present 
      tags:
        Name: "terminate"
    delegate_to: localhost
